/**
 * @vitest-environment jsdom
 */
import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { beforeEach, describe, expect, it, vi } from "vitest";

import type { Itinerary } from "@/lib/trips/itinerary";

const { mockRefresh, mockSubmit, useObjectState } = vi.hoisted(() => ({
  mockRefresh: vi.fn(),
  mockSubmit: vi.fn(),
  useObjectState: {
    object: undefined as Itinerary | undefined,
    isLoading: false,
    error: undefined as Error | undefined,
  },
}));

vi.mock("next/navigation", () => ({
  useRouter: () => ({ refresh: mockRefresh }),
}));

vi.mock("@ai-sdk/react", () => ({
  experimental_useObject: () => ({
    submit: mockSubmit,
    get object() {
      return useObjectState.object;
    },
    get isLoading() {
      return useObjectState.isLoading;
    },
    get error() {
      return useObjectState.error;
    },
  }),
}));

import { ItineraryGenerator } from "./itinerary-generator";

const completeItinerary: Itinerary = {
  days: [
    {
      day: 1,
      title: "Historic centre",
      activities: [
        {
          name: "Museum",
          description: "City museum",
          approxCostEur: 12,
        },
      ],
    },
  ],
  totalApproxCostEur: 12,
};

describe("ItineraryGenerator — NFR loading state (PRD)", () => {
  beforeEach(() => {
    mockRefresh.mockClear();
    mockSubmit.mockClear();
    useObjectState.object = undefined;
    useObjectState.isLoading = false;
    useObjectState.error = undefined;
  });

  it("does not show loading UI before the user starts generation", () => {
    render(<ItineraryGenerator tripId="trip-1" />);

    expect(screen.queryByRole("status")).not.toBeInTheDocument();
    expect(
      screen.queryByText(/Generating your itinerary/i),
    ).not.toBeInTheDocument();
    expect(
      screen.getByRole("button", { name: /generate itinerary/i }),
    ).toBeInTheDocument();
  });

  it("shows an accessible loading state while generation is in progress", async () => {
    useObjectState.isLoading = true;
    const user = userEvent.setup();

    render(<ItineraryGenerator tripId="trip-1" />);
    await user.click(
      screen.getByRole("button", { name: /generate itinerary/i }),
    );

    const status = screen.getByRole("status");
    expect(status).toHaveAttribute("aria-busy", "true");
    expect(status).toHaveTextContent("Generating your itinerary…");
    expect(
      screen.getByText(/usually takes 15–30 seconds/i),
    ).toBeInTheDocument();
    expect(mockSubmit).toHaveBeenCalledWith({});
  });

  it("replaces loading UI with itinerary and disclaimer when generation completes", async () => {
    useObjectState.object = completeItinerary;
    const user = userEvent.setup();

    render(<ItineraryGenerator tripId="trip-1" />);
    await user.click(
      screen.getByRole("button", { name: /generate itinerary/i }),
    );

    expect(screen.queryByRole("status")).not.toBeInTheDocument();
    expect(
      screen.getByText(/All costs are estimates generated by AI/i),
    ).toBeInTheDocument();
    expect(screen.getByText("Museum")).toBeInTheDocument();
  });

  it("shows an error alert when generation fails", async () => {
    useObjectState.error = new Error("upstream failure");
    const user = userEvent.setup();

    render(<ItineraryGenerator tripId="trip-1" />);
    await user.click(
      screen.getByRole("button", { name: /generate itinerary/i }),
    );

    expect(screen.getByRole("alert")).toHaveTextContent(
      /Generation failed — please try again/i,
    );
    expect(
      screen.getByRole("button", { name: /try again/i }),
    ).toBeInTheDocument();
  });
});
