import { describe, expect, it } from "vitest";

import {
  dayCost,
  DISCLAIMER,
  tripTotalCost,
  type PartialItinerary,
} from "./itinerary-view";

describe("DISCLAIMER — FR-010 cost estimate labelling", () => {
  it("matches the PRD-required estimate disclaimer text", () => {
    expect(DISCLAIMER).toBe(
      "All costs are estimates generated by AI. Actual prices may vary.",
    );
  });
});

describe("dayCost — FR-010 per-day approximate cost from activities", () => {
  it("sums activity approxCostEur values for a day", () => {
    expect(
      dayCost([
        { approxCostEur: 10 },
        { approxCostEur: 25 },
        { approxCostEur: 0 },
      ]),
    ).toBe(35);
  });

  it("treats missing or non-numeric costs as zero", () => {
    expect(dayCost([undefined, {}, { approxCostEur: 5 }])).toBe(5);
    expect(dayCost()).toBe(0);
  });
});

describe("tripTotalCost — FR-010 derived total from activity costs", () => {
  const itinerary: PartialItinerary = {
    days: [
      {
        activities: [{ approxCostEur: 20 }, { approxCostEur: 10 }],
      },
      {
        activities: [{ approxCostEur: 15 }],
      },
    ],
    totalApproxCostEur: 999,
  };

  it("sums costs across all days from activities, not totalApproxCostEur", () => {
    // PRD: original AI total is preserved separately; derived sum is from activities.
    expect(tripTotalCost(itinerary)).toBe(45);
  });

  it("returns zero for empty or missing days", () => {
    expect(tripTotalCost({})).toBe(0);
    expect(tripTotalCost({ days: [] })).toBe(0);
    expect(tripTotalCost({ days: [undefined, { activities: [] }] })).toBe(0);
  });
});
