import { formatBudget } from "@/components/trip-card";

// Loose, deeply-partial shape: the same component renders a fully-saved
// itinerary (read-only) and a mid-stream partial object, so every field is
// treated as possibly-undefined.
type PartialActivity = {
  name?: string;
  description?: string;
  approxCostEur?: number;
};
type PartialDay = {
  day?: number;
  title?: string;
  activities?: Array<PartialActivity | undefined>;
};
export type PartialItinerary = {
  days?: Array<PartialDay | undefined>;
  totalApproxCostEur?: number;
};

export const DISCLAIMER =
  "All costs are estimates generated by AI. Actual prices may vary.";

export function dayCost(
  activities: Array<PartialActivity | undefined> = [],
): number {
  return activities.reduce(
    (sum, a) => sum + (typeof a?.approxCostEur === "number" ? a.approxCostEur : 0),
    0,
  );
}

export function tripTotalCost(itinerary: PartialItinerary): number {
  const days = (itinerary.days ?? []).filter((d): d is PartialDay => d != null);
  return days.reduce((sum, day) => {
    const activities = (day.activities ?? []).filter(
      (a): a is PartialActivity => a != null,
    );
    return sum + dayCost(activities);
  }, 0);
}

export function ItineraryView({ itinerary }: { itinerary: PartialItinerary }) {
  const days = (itinerary.days ?? []).filter(
    (d): d is PartialDay => d != null,
  );

  return (
    <div className="flex flex-col gap-4">
      <ul className="flex flex-col gap-4">
        {days.map((day, i) => {
          const activities = (day.activities ?? []).filter(
            (a): a is PartialActivity => a != null,
          );
          return (
            <li
              key={i}
              className="rounded-lg border border-zinc-200 bg-white p-4 dark:border-zinc-800 dark:bg-zinc-950"
            >
              <div className="flex items-baseline justify-between gap-3">
                <h3 className="font-medium text-zinc-900 dark:text-zinc-50">
                  Day {day.day ?? i + 1}
                  {day.title ? ` · ${day.title}` : ""}
                </h3>
                {activities.length > 0 ? (
                  <span className="text-sm text-zinc-500 dark:text-zinc-400">
                    {formatBudget(dayCost(activities))}
                  </span>
                ) : null}
              </div>
              <ul className="mt-2 flex flex-col gap-2">
                {activities.map((activity, j) => (
                  <li key={j} className="flex justify-between gap-3 text-sm">
                    <span className="text-zinc-700 dark:text-zinc-300">
                      <span className="font-medium text-zinc-900 dark:text-zinc-100">
                        {activity.name ?? "…"}
                      </span>
                      {activity.description ? ` — ${activity.description}` : ""}
                    </span>
                    {typeof activity.approxCostEur === "number" ? (
                      <span className="shrink-0 text-zinc-500 dark:text-zinc-400">
                        {formatBudget(activity.approxCostEur)}
                      </span>
                    ) : null}
                  </li>
                ))}
              </ul>
            </li>
          );
        })}
      </ul>

      {typeof itinerary.totalApproxCostEur === "number" ? (
        <p className="text-right font-medium text-zinc-900 dark:text-zinc-50">
          Estimated total: {formatBudget(itinerary.totalApproxCostEur)}
        </p>
      ) : null}

      <p className="text-xs text-zinc-500 dark:text-zinc-400">{DISCLAIMER}</p>
    </div>
  );
}
