import { formatBudget } from "@/lib/format";

type PartialActivity = {
  name?: string;
  description?: string;
  approxCostEur?: number;
};
type PartialDay = {
  day?: number;
  title?: string;
  activities?: Array<PartialActivity | undefined>;
};
export type PartialItinerary = {
  days?: Array<PartialDay | undefined>;
  totalApproxCostEur?: number;
};

export const DISCLAIMER =
  "All costs are estimates generated by AI. Actual prices may vary.";

export function dayCost(
  activities: Array<PartialActivity | undefined> = [],
): number {
  return activities.reduce(
    (sum, a) => sum + (typeof a?.approxCostEur === "number" ? a.approxCostEur : 0),
    0,
  );
}

export function tripTotalCost(itinerary: PartialItinerary): number {
  const days = (itinerary.days ?? []).filter((d): d is PartialDay => d != null);
  return days.reduce((sum, day) => {
    const activities = (day.activities ?? []).filter(
      (a): a is PartialActivity => a != null,
    );
    return sum + dayCost(activities);
  }, 0);
}

export function ItineraryView({ itinerary }: { itinerary: PartialItinerary }) {
  const days = (itinerary.days ?? []).filter(
    (d): d is PartialDay => d != null,
  );

  return (
    <div className="grid gap-5">
      <ul className="grid gap-4">
        {days.map((day, i) => {
          const activities = (day.activities ?? []).filter(
            (a): a is PartialActivity => a != null,
          );
          return (
            <li
              key={i}
              className="rounded-[28px] border border-[var(--border-muted)] bg-white p-6 shadow-[0_20px_60px_rgba(49,33,20,0.07)]"
            >
              <div className="flex items-baseline justify-between gap-3">
                <h3 className="text-lg font-black text-[var(--foreground)]">
                  Day {day.day ?? i + 1}
                  {day.title ? `: ${day.title}` : ""}
                </h3>
                {activities.length > 0 ? (
                  <span className="text-sm text-[var(--muted)]">
                    {formatBudget(dayCost(activities))}
                  </span>
                ) : null}
              </div>
              <ul className="mt-4 grid gap-3">
                {activities.map((activity, j) => (
                  <li
                    key={j}
                    className="flex justify-between gap-3 rounded-[18px] bg-[var(--surface-muted)] p-4 text-sm"
                  >
                    <span className="text-[var(--foreground)]">
                      <span className="font-bold">{activity.name ?? "…"}</span>
                      {activity.description ? (
                        <span className="text-[var(--muted)]">
                          {" "}
                          — {activity.description}
                        </span>
                      ) : null}
                    </span>
                    {typeof activity.approxCostEur === "number" ? (
                      <span className="shrink-0 font-semibold text-[var(--muted)]">
                        {formatBudget(activity.approxCostEur)}
                      </span>
                    ) : null}
                  </li>
                ))}
              </ul>
            </li>
          );
        })}
      </ul>

      {typeof itinerary.totalApproxCostEur === "number" ? (
        <p className="text-right font-bold text-[var(--foreground)]">
          Estimated total: {formatBudget(itinerary.totalApproxCostEur)}
        </p>
      ) : null}

      <p className="text-xs text-[var(--muted-light)]">{DISCLAIMER}</p>
    </div>
  );
}
